# docker-compose.yml
version: '3'

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-lakehouse
    container_name: spark
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "5000:5000"
      - "8000:8000"
    networks:
      - spark-network
    command: >
      bash -c "mkdir -p data/{bronze,silver,gold} & mlflow ui --host 0.0.0.0 --port 8000 & python /app/src/app.py & tail -f /dev/null"

networks:
  spark-network:
    driver: bridge